events {}

http {
  log_format waf '$remote_addr - $time_local '
                 '"$request" $status '
                 'limit=$limit_req_status '
                 'up=$upstream_status '
                 'rt=$request_time urt=$upstream_response_time '
                 'ua="$http_user_agent"';

  access_log /var/log/nginx/access.log waf;

  limit_req_zone $binary_remote_addr zone=rate_limit:10m rate=1r/s;
  limit_req_status 429;

  server {
    listen 80;

    add_header X-CATE-Limit $limit_req_status always;
    add_header X-CATE-Upstream $upstream_status always;

    location / {
      limit_req zone=rate_limit burst=2 nodelay;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_connect_timeout 2s;
      proxy_read_timeout 5s;

      proxy_pass http://app:8080;
    }

    error_page 429 = @rate_limited;

    location @rate_limited {
      add_header X-CATE-WAF "rate_limited" always;
      default_type text/html;
      return 429 "<html><body><h1>Blocked</h1><p>Rate limit exceeded</p></body></html>";
    }
  }
}
