# cate/logging_utils.py
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence

from .models import Result


# -----------------------------
# Helpers
# -----------------------------
def _normalize_output_prefix(output_prefix: str) -> Path:
    """
    Normalize output prefix to a base path used for sibling artifacts.

    If caller passes "...something.jsonl", treat that as the run artifact name
    and drop the suffix so signals become:
      something.signals.json
      something.signals.md
    """
    out = Path(output_prefix)
    if out.suffix.lower() == ".jsonl":
        out = out.with_suffix("")
    return out


# -----------------------------
# Results
# -----------------------------
def write_results_jsonl(path: Path, results: Iterable[Result]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in results:
            data = asdict(r)
            data["timestamp"] = r.timestamp.isoformat() + "Z"
            f.write(json.dumps(data) + "\n")


# -----------------------------
# Flow summary markdown
# -----------------------------
def render_flow_summary_md(
    results: Sequence[Mapping[str, Any]],
    env: Optional[str] = None,
    initial_vars: Optional[Dict[str, Any]] = None,
) -> str:
    total = len(results)
    failing = [r for r in results if not r.get("ok")]
    failures = len(failing)
    passed = (total > 0 and failures == 0)
    avg_ms = (
        sum(r.get("elapsed_ms", 0.0) for r in results) / total
        if total > 0
        else 0.0
    )

    final_vars: Dict[str, Any] = {}
    for r in results:
        var_name = r.get("extracted_var")
        var_value = r.get("extracted_value")
        if var_name is not None and var_value is not None:
            final_vars[var_name] = var_value

    lines: List[str] = []
    lines.append("# ✅ Flow Passed" if passed else "# ❌ Flow Failed")
    lines.append("")

    lines.append("## Overview")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Steps | {total} |")
    lines.append(f"| Failures | {failures} |")
    lines.append(f"| Avg latency | {avg_ms:.2f} ms |")

    if env is not None:
        lines.append(f"| Env | {env} |")

    if initial_vars:
        var_keys = ", ".join(sorted(str(k) for k in initial_vars.keys()))
        lines.append(f"| Seeded vars | {var_keys} |")

    lines.append("")

    if failing:
        lines.append("## Failing Steps")
        lines.append("")
        lines.append("| Step | Method | URL | Status | Time (ms) | Error |")
        lines.append("|------|--------|-----|--------|-----------|--------|")
        for r in failing:
            step = r.get("step", "")
            method = r.get("method", "")
            url = str(r.get("url", "")).replace("|", "\\|")
            status = r.get("status_code", "None")
            latency = r.get("elapsed_ms", "–")
            error = str(r.get("error") or "").replace("|", "\\|")
            lines.append(f"| {step} | {method} | {url} | {status} | {latency} | {error} |")
        lines.append("")

    if results:
        lines.append("## All Steps")
        lines.append("")
        lines.append("| Step | Method | URL | Status | OK | Latency (ms) | Bytes | Error |")
        lines.append("|------|--------|-----|--------|----|-------------:|------:|-------|")
        for r in results:
            step = r.get("step", "")
            method = r.get("method", "")
            url = str(r.get("url", "")).replace("|", "\\|")
            status = r.get("status_code", "None")
            ok = "✅" if r.get("ok") else "❌"
            latency = f"{r.get('elapsed_ms', 0.0):.1f}"
            size = r.get("bytes", 0)
            error = str(r.get("error") or "").replace("|", "\\|")
            lines.append(
                f"| {step} | {method} | {url} | {status} | {ok} | {latency} | {size} | {error} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("_Report generated by **CATE**_")
    return "\n".join(lines).rstrip() + "\n"


# -----------------------------
# Signals artifacts
# -----------------------------
def write_signals_json(signals: Dict[str, Any], output_prefix: str) -> str:
    """
    Writes <prefix>.signals.json, returns the path as a string.
    """
    out = _normalize_output_prefix(output_prefix)
    path = out.with_suffix(".signals.json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(signals, indent=2, sort_keys=True, default=str),
        encoding="utf-8",
    )
    return str(path)


def write_signals_md(signals: Dict[str, Any], output_prefix: str) -> str:
    """
    Writes <prefix>.signals.md, returns the path as a string.
    """
    out = _normalize_output_prefix(output_prefix)
    path = out.with_suffix(".signals.md")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_signals_md(signals), encoding="utf-8")
    return str(path)


def render_signals_md(signals: Dict[str, Any]) -> str:
    """
    Deterministic markdown renderer for signals (stable ordering).
    """
    kind = str(signals.get("kind", "run"))
    ok = bool(signals.get("ok", False))
    severity = str(signals.get("severity", "none")).upper()

    notes_raw = signals.get("notes") or []
    if not isinstance(notes_raw, list):
        notes_raw = []
    notes = sorted(str(n) for n in notes_raw)

    lines: List[str] = []
    lines.append(f"# CATE Signals — {severity}")
    lines.append("")
    lines.append(f"- **Kind:** `{kind}`")
    lines.append(f"- **OK:** `{ok}`")
    if notes:
        lines.append(f"- **Notes:** `{', '.join(notes)}`")
    else:
        lines.append("- **Notes:** `none`")
    lines.append("")

    tf = signals.get("top_failure")
    if isinstance(tf, dict) and tf:
        lines.append("## Top failure")
        step = tf.get("step")
        expected = tf.get("expected")
        status = tf.get("status")
        error = tf.get("error")
        if step is not None:
            lines.append(f"- Step: **{step}**")
        if expected is not None:
            lines.append(f"- Expected: **{expected}**")
        if status is not None:
            lines.append(f"- Got: **{status}**")
        if error:
            lines.append(f"- Error: `{error}`")
        lines.append("")

    tt = signals.get("top_trigger")
    if isinstance(tt, str) and tt:
        lines.append("## Top trigger")
        lines.append(f"- Payload: `{tt}`")
        lines.append("")

    counts = signals.get("counts") or {}
    if not isinstance(counts, dict):
        counts = {}

    lines.append("## Counts")
    lines.append("")

    if kind == "http-flow":
        for k, label in (("steps", "Steps"), ("failures", "Failures"), ("failure_rate", "Failure rate")):
            if k in counts:
                lines.append(f"- {label}: **{counts[k]}**")
    elif kind == "http-fuzz":
        for k, label in (("total_payloads", "Total payloads"), ("error_count", "Error count"), ("error_rate", "Error rate")):
            if k in counts:
                lines.append(f"- {label}: **{counts[k]}**")

        status_counts = counts.get("status_counts") or {}
        if isinstance(status_counts, dict) and status_counts:
            lines.append("")
            lines.append("### Status codes")
            lines.append("")

            def _status_sort_key(x: Any):
                try:
                    return (0, int(x))
                except Exception:
                    return (1, str(x))

            for code in sorted(status_counts.keys(), key=_status_sort_key):
                lines.append(f"- `{code}`: **{status_counts[code]}**")
    else:
        for k in sorted(counts.keys()):
            lines.append(f"- {k}: **{counts[k]}**")

    latency = signals.get("latency") or {}
    if isinstance(latency, dict) and latency:
        lines.append("")
        lines.append("## Latency (ms)")
        lines.append("")
        preferred = ["avg_ms", "p50_ms", "p90_ms", "p99_ms"]
        seen = set()
        for k in preferred:
            if k in latency:
                lines.append(f"- `{k}`: **{latency[k]}**")
                seen.add(k)
        for k in sorted(latency.keys()):
            if k not in seen:
                lines.append(f"- `{k}`: **{latency[k]}**")

    return "\n".join(lines).rstrip() + "\n"
