# cate/logging_utils.py
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Iterable

from .models import Result


def write_results_jsonl(path: Path, results: Iterable[Result]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in results:
            data = asdict(r)
            # ISO format for datetime
            data["timestamp"] = r.timestamp.isoformat() + "Z"
            f.write(json.dumps(data) + "\n")

from typing import Sequence, Mapping, Any


def write_flow_summary_md(path: Path, flow_name: str, steps: Sequence[Mapping[str, Any]]) -> None:
    """
    Render a clean, GitHub-friendly Markdown summary for http-flow runs.

    `steps` is expected to be a list of dicts like:
      {
        "step": "login",
        "method": "POST",
        "url": "https://…",
        "status_code": 200,
        "ok": True/False,
        "elapsed_ms": 123.4,
        "bytes": 2512,
        "error": "..." or None,
      }
    """

    # Flow passes only if all steps are ok
    passed = all(step.get("ok", False) for step in steps) if steps else False
    failing = [s for s in steps if not s.get("ok", False)]

    lines: list[str] = []

    # 1. Header
    if passed:
        lines.append("# ✅ Flow Passed")
    else:
        lines.append("# ❌ Flow Failed")

    if flow_name:
        lines.append(f"### **{flow_name}**")
    lines.append("")

    # 2. Failing steps (if any)
    if failing:
        lines.append("## Failing Steps\n")
        lines.append("| Step | Method | URL | Status | Time (ms) | Error |")
        lines.append("|------|--------|-----|--------|-----------|--------|")

        for s in failing:
            lines.append(
                f"| {s.get('step', '')} "
                f"| {s.get('method', '')} "
                f"| {s.get('url', '')} "
                f"| {s.get('status_code', 'None')} "
                f"| {s.get('elapsed_ms', '–')} "
                f"| {s.get('error', '') or ''} |"
            )
        lines.append("")

    # 3. All steps
    if steps:
        lines.append("## All Steps\n")
        lines.append("| Step | Method | Status | Time (ms) | Bytes | OK? |")
        lines.append("|------|--------|--------|-----------|-------|-----|")

        for s in steps:
            ok_flag = "✅" if s.get("ok") else "❌"
            lines.append(
                f"| {s.get('step', '')} "
                f"| {s.get('method', '')} "
                f"| {s.get('status_code', 'None')} "
                f"| {s.get('elapsed_ms', '–')} "
                f"| {s.get('bytes', '–')} "
                f"| {ok_flag} |"
            )
        lines.append("")

        # 3.5 Recon observations (only if present)
        recon_steps = [s for s in steps if isinstance(s.get("recon"), dict) and s.get("recon")]

        if recon_steps:
            lines.append("## Recon Observations\n")

            for s in recon_steps:
                step_name = s.get("step", "")
                recon = s.get("recon", {})

                lines.append(f"### Step {step_name}\n")

                # Redirect chain
                chain = recon.get("redirect_chain")
                if chain:
                    lines.append("**Redirect chain:**")
                    for hop in chain:
                        lines.append(f"- {hop}")
                    lines.append("")

                # Header fingerprints
                headers = recon.get("headers")
                if isinstance(headers, dict) and headers:
                    lines.append("**Observed headers:**")
                    for k, v in headers.items():
                        lines.append(f"- `{k}`: `{v}`")
                    lines.append("")

                # Body fingerprint / hash
                body_hash = recon.get("body_hash")
                if body_hash:
                    lines.append(f"**Body fingerprint:** `{body_hash}`\n")


    # 4. Footer
    lines.append("---")
    lines.append("_Report generated by **CATE v0.3 — Calypso Automated Testing Engine**_")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
